baseURL = 'https://videohubapp.com'
title = 'Video Hub App'
disableKinds = ["taxonomy"]
enableRobotsTXT = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = "en-US"
    weight = 1
  [languages.es]
    contentDir = 'content/es'
    languageCode = "es-ES"
    weight = 2
[params]
  latestVersion = '3.2.0'
